### ISSUE TITLE
RuntimeError:An attempt has been made to start a new process before the， current process has finished its bootstrapping phase.

### ISSUE THREAD

**Issue by Hankerlove** [lyc0929/OOTDiffusion-train#7]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\86187\.conda\envs\ootd\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\86187\.conda\envs\ootd\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\86187\.conda\envs\ootd\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\BUPT-course\VTON\OOTDiffusion\run\ootd_train.py", line 148, in <module>
    test_loader = VITONDataLoader(opt, test_dataset)
  File "E:\BUPT-course\VTON\OOTDiffusion\run\utils\dataloader.py", line 218, in __init__
    self.data_iter = self.data_loader.__iter__()
  File "C:\Users\86187\.conda\envs\ootd\lib\site-packages\torch\utils\data\dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "C:\Users\86187\.conda\envs\ootd\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\86187\.conda\envs\ootd\lib\site-packages\torch\utils\data\dataloader.py", line 1042, in __init__
    w.start()
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\86187\.conda\envs\ootd\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by zhangquanwei962** [comment]
Hi, our code is only tested on **Linux OS**, so it may not be good at **Windows OS**. BTW, I think you can modify the code as ``` if __name__ == '__main__:  
                main()
```
which can be a good attempt to solve this problem. Please note that the functional `main()` means all code you will run, moving them to a functional or changing the process worker is **1** or **0**.
